name: ESP32 MicroPython Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'ports/esp32/**'
      - '.github/workflows/*.yml'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master
    paths:
      - 'ports/esp32/**'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MICROPYTHON_DIR: ~/micropython
  ESP_IDF_DIR: ~/esp-idf
  ARTIFACTS_DIR: ~/artifacts
  MPY_VERSION: v1.25.0
  ESP_IDF_VERSION: v5.4.1

jobs:
  setup-environment:
    runs-on: ubuntu-24.04
    steps:
      - name: Cache ESP-IDF and MicroPython
        id: cache_esp_idf
        uses: actions/cache@v4
        with:
          lookup-only: true
          path: |
            ${{ env.ESP_IDF_DIR }}
            ~/.espressif/
            ~/.cache/pip/
            ${{ env.MICROPYTHON_DIR }}
          key: mpy-${{ env.MPY_VERSION }}-idf-${{ env.ESP_IDF_VERSION }}
          restore-keys: |
            mpy-${{ env.MPY_VERSION }}-idf-
            mpy-

      - name: Install dependencies (if not cached)
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget flex bison gperf \
            python3 python3-pip python3-venv \
            cmake ninja-build ccache \
            libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Clone MicroPython (if not cached)
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          cd ~
          git clone --depth 1 --branch ${{ env.MPY_VERSION }} \
            https://github.com/micropython/micropython.git ${{ env.MICROPYTHON_DIR }}
          cd ${{ env.MICROPYTHON_DIR }}
          git submodule update --init --depth 1
          make -C mpy-cross

      - name: Setup ESP-IDF (if not cached)
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          cd ~
          git clone --depth 1 --branch ${{ env.ESP_IDF_VERSION }} \
            https://github.com/espressif/esp-idf.git ${{ env.ESP_IDF_DIR }}
          cd ${{ env.ESP_IDF_DIR }}
          ./install.sh esp32,esp32s3,esp32c3
          source ./export.sh

  build:
    needs: setup-environment
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { board: "ESP32_GENERIC_S3", variant: "SPIRAM_OCT", flash_size: "16" }
          - { board: "ESP32_GENERIC_C3", variant: "", flash_size: "8" }
          - { board: "ESP32_GENERIC", variant: "SPIRAM", flash_size: "4" }

    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESP_IDF_DIR }}
            ~/.espressif/
            ~/.cache/pip/
            ${{ env.MICROPYTHON_DIR }}
          key: mpy-${{ env.MPY_VERSION }}-idf-${{ env.ESP_IDF_VERSION }}
          restore-keys: |
            mpy-${{ env.MPY_VERSION }}-idf-
            mpy-

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build MicroPython
        run: |
          source ${{ env.ESP_IDF_DIR }}/export.sh
          cd ${{ env.MICROPYTHON_DIR }}/ports/esp32

          # 准备构建命令
          BUILD_DIR="build-${{ matrix.config.board }}"
          [ -n "${{ matrix.config.variant }}" ] && BUILD_DIR="${BUILD_DIR}-${{ matrix.config.variant }}"
          
          IDF_CMD="idf.py \
            -D MICROPY_DIR=${{ env.MICROPYTHON_DIR }} \
            -D MICROPY_BOARD=${{ matrix.config.board }} \
            -D MICROPY_FLASH_SIZE=${{ matrix.config.flash_size }}MB \
            -B $BUILD_DIR"
          
          # 添加variant参数（如果存在）
          if [ -n "${{ matrix.config.variant }}" ]; then
              IDF_CMD="$IDF_CMD -D MICROPY_BOARD_VARIANT=${{ matrix.config.variant }}"
          fi

          echo "Building with command: $IDF_CMD"
          eval "$IDF_CMD build"

          # 生成固件镜像
          cd $BUILD_DIR
          python ../makeimg.py \
            sdkconfig \
            bootloader/bootloader.bin \
            partition_table/partition-table.bin \
            micropython.bin \
            firmware.bin \
            micropython.uf2

          # 整理构建产物
          mkdir -p ${{ env.ARTIFACTS_DIR }}
          FIRMWARE_NAME="firmware-${{ matrix.config.board }}"
          [ -n "${{ matrix.config.variant }}" ] && FIRMWARE_NAME="${FIRMWARE_NAME}-${{ matrix.config.variant }}"
          FIRMWARE_NAME="${FIRMWARE_NAME}-${{ matrix.config.flash_size }}MB.bin"
          
          mv firmware.bin ${{ env.ARTIFACTS_DIR }}/$FIRMWARE_NAME

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.config.board }}-${{ matrix.config.variant }}-${{ matrix.config.flash_size }}MB
          path: ${{ env.ARTIFACTS_DIR }}/firmware-${{ matrix.config.board }}-${{ matrix.config.variant }}-${{ matrix.config.flash_size }}MB.bin
          retention-days: 7

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.config.board }}-${{ matrix.config.variant }}
          path: ${{ env.MICROPYTHON_DIR }}/ports/esp32/build-${{ matrix.config.board }}/log/
          retention-days: 7
